[package]
name = "adventofcode-2020"
version = "0.1.0"
authors = ["Roel van Duijnhoven <roel@vanduijnhoven.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combinations = "0.1.0"
regex = "1"